## YAML Template.
---
server:
  port: 8081

eureka:
  client:
    service-url: 
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
logging:
  level:
    org.springframework.cloud.gateway: Debug
    reactor.netty.http.client: DEBUG
spring:
  application:
    name: businessdomain-customer
  cloud:
    gateway:
      routes:
      - id: customer_service
        uri: lb://businessdomain-customer
        predicates:
        - Path=/**
    config:
       enabled: false 