## YAML Template.
---
server:
  port: 8081

eureka:
  client:
    service-url: 
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    org.springframework.cloud.gateway: Debug
    reactor.netty.http.client: DEBUG
spring:
  application:
    name: businessdomain-customer
  cloud:
    gateway:
      routes:
      - id: customer_service
        uri: lb://businessdomain-customer
        predicates:
        - Path=/business-customer/**
      - id: product_service
        uri: lb://businessdomain-product
        predicates:
        - Path=/business-product/**
      - id: transaction_service
        uri: lb://businessdomain-transaction
        predicates:
        - Path=/business-transaction/**
    config:
       enabled: false 