version: '3.8'
services:
  registry-discovery:
    container_name: eureka_container
    image: eureka_image2:latest
    networks:
      - red-paymentchain
    ports:
      - "8761:8761"
    environment:
      - JAVA_OPTS=-Xms256M -Xmx256M

  apigateway:
    container_name: apigateway_container
    image: apigateway_image2:latest
    networks:
      - red-paymentchain
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-Xms256M -Xmx256M
      - EUREKA_SERVER=http://registry-discovery:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  product-catalog:
    container_name: product_container
    image: product_image2:latest
    networks:
      - red-paymentchain
    environment:
      - JAVA_OPTS=-Xms256M -Xmx256M
      - EUREKA_SERVER=http://registry-discovery:8761/eureka/
    depends_on:
      - registry-discovery
    ports:
      - "8083:8083"

  customer:
    container_name: customer_container
    image: customer_image2:latest
    networks:
      - red-paymentchain
    environment:
      - JAVA_OPTS=-Xms256M -Xmx256M
      - EUREKA_SERVER=http://registry-discovery:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    depends_on:
      - registry-discovery
  
  keycloak:
    container_name: keycloakAdapter
    image: keycloak_image:latest  
    networks:
      - red-paymentchain
    environment:
      - JAVA_OPTS=-Xms256M -Xmx256M
      - EUREKA_SERVER=http://registry-discovery:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - KEYCLOAK_SERVER=http://keycloak_server:8080/realms/
      - KEYCLOAK_REAL_ID=Sg-SyKcNLOTcuu-MxlVU6_WgBArNZtsAmTDK-QoNVHM
    depends_on:
      - registry-discovery
    ports:
      - "8088:8088"

  transactions:
    container_name: transaction_container
    image: transaction_image2:latest
    networks:
      - red-paymentchain
    environment:
      - JAVA_OPTS=-Xms256M -Xmx256M
      - EUREKA_SERVER=http://registry-discovery:8761/eureka/
    depends_on:
      - registry-discovery
    ports:
      - "8082:8082"

  postgres_db:
    container_name: postgres
    image: postgres:latest
    networks:
      - red-paymentchain
    ports:
      - "5432:5432"
    volumes:
      - ./dbfiles:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres

  pgadmin4:
    image: dpage/pgadmin4
    networks:
      - red-paymentchain
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: qwerty
    ports:
      - "80:80"
    depends_on:
      - postgres_db
      
  keycloak_server:
    container_name: id-keycloakServer
    image: quay.io/keycloak/keycloak:latest
    networks:
      - red-paymentchain
    restart: always
    ports:
      - 8091:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: [ "start-dev" ]

networks:
  red-paymentchain:
    driver: bridge
    attachable: true
    external: true
